# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/input.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'app/input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61pp/input.proto\"q\n\nKeyOptions\x12\x16\n\tno_repeat\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x19\n\x0cno_modifiers\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x11\n\tmodifiers\x18\x03 \x03(\x05\x42\x0c\n\n_no_repeatB\x0f\n\r_no_modifiers\"^\n\x03Key\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1c\n\x04type\x18\x02 \x01(\x0e\x32\x0e.KeyActionType\x12!\n\x07options\x18\x03 \x01(\x0b\x32\x0b.KeyOptionsH\x00\x88\x01\x01\x42\n\n\x08_options\"Y\n\rHotkeyOptions\x12\x12\n\x05speed\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x19\n\x0cno_modifiers\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x08\n\x06_speedB\x0f\n\r_no_modifiers\"h\n\x06Hotkey\x12\x0e\n\x06hotkey\x18\x01 \x01(\t\x12\x1c\n\x04type\x18\x02 \x01(\x0e\x32\x0e.KeyActionType\x12$\n\x07options\x18\x03 \x01(\x0b\x32\x0e.HotkeyOptionsH\x00\x88\x01\x01\x42\n\n\x08_options\"k\n\x08MouseKey\x12\n\n\x02id\x18\x01 \x01(\x05\x12%\n\x04type\x18\x02 \x01(\x0e\x32\x17.MouseKey.KeyActionType\",\n\rKeyActionType\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\t\n\x05PRESS\x10\x03\"3\n\tMouseMove\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x10\n\x08relative\x18\x03 \x01(\x08\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"n\n\x06\x43onfig\x12\x19\n\x0c\x63ursor_speed\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12 \n\x13\x63ursor_acceleration\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\x0f\n\r_cursor_speedB\x16\n\x14_cursor_acceleration\"\x07\n\x05\x45mpty*,\n\rKeyActionType\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\t\n\x05PRESS\x10\x03\x32\xf1\x01\n\x0cInputMethods\x12\x1b\n\x08PressKey\x12\x04.Key\x1a\t.Response\x12!\n\x0bPressHotkey\x12\x07.Hotkey\x1a\t.Response\x12%\n\rPressMouseKey\x12\t.MouseKey\x1a\t.Response\x12\"\n\tMoveMouse\x12\n.MouseMove\x1a\t.Response\x12\x19\n\x04Ping\x12\x06.Empty\x1a\t.Response\x12\x1d\n\tSetConfig\x12\x07.Config\x1a\x07.Config\x12\x1c\n\tGetConfig\x12\x06.Empty\x1a\x07.Configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYACTIONTYPE']._serialized_start=490
  _globals['_KEYACTIONTYPE']._serialized_end=534
  _globals['_KEYOPTIONS']._serialized_start=19
  _globals['_KEYOPTIONS']._serialized_end=132
  _globals['_KEY']._serialized_start=134
  _globals['_KEY']._serialized_end=228
  _globals['_HOTKEYOPTIONS']._serialized_start=230
  _globals['_HOTKEYOPTIONS']._serialized_end=319
  _globals['_HOTKEY']._serialized_start=321
  _globals['_HOTKEY']._serialized_end=425
  _globals['_MOUSEKEY']._serialized_start=427
  _globals['_MOUSEKEY']._serialized_end=534
  _globals['_MOUSEKEY_KEYACTIONTYPE']._serialized_start=490
  _globals['_MOUSEKEY_KEYACTIONTYPE']._serialized_end=534
  _globals['_MOUSEMOVE']._serialized_start=536
  _globals['_MOUSEMOVE']._serialized_end=587
  _globals['_RESPONSE']._serialized_start=589
  _globals['_RESPONSE']._serialized_end=616
  _globals['_CONFIG']._serialized_start=618
  _globals['_CONFIG']._serialized_end=728
  _globals['_EMPTY']._serialized_start=730
  _globals['_EMPTY']._serialized_end=737
  _globals['_INPUTMETHODS']._serialized_start=786
  _globals['_INPUTMETHODS']._serialized_end=1027
# @@protoc_insertion_point(module_scope)
