import dataclasses

# USB Usage ID values for the keycodes that TinyPilot can emit to the target
# computer through the USB keyboard interface.
#
# Source: HID Usage Tables for USB, v1.21, section "10 - Keyboard/Keypad Page"
# https://usb.org/sites/default/files/hut1_21.pdf

MODIFIER_LEFT_CTRL = 1 << 0
MODIFIER_LEFT_SHIFT = 1 << 1
MODIFIER_LEFT_ALT = 1 << 2
MODIFIER_LEFT_META = 1 << 3
MODIFIER_RIGHT_CTRL = 1 << 4
MODIFIER_RIGHT_SHIFT = 1 << 5
MODIFIER_RIGHT_ALT = 1 << 6
MODIFIER_RIGHT_META = 1 << 7
# The "Alt Gr" key is a special modifier key that is present on e.g. German
# keyboards. There are multiple ways to emulate this key, e.g. by (a) just
# using the "Right Alt" modifier, or (b) by using "Left Alt"+"Left Ctrl". In
# our tests, we found that (a) seems to be the most compatible option, as it
# appears to work on both Windows and Linux systems, whereas (b) appears to
# only work reliably on Windows systems.
MODIFIER_ALT_GR = MODIFIER_RIGHT_ALT

modifier_keys = [
    MODIFIER_LEFT_CTRL,
    MODIFIER_LEFT_SHIFT,
    MODIFIER_LEFT_ALT,
    MODIFIER_LEFT_META,
    MODIFIER_RIGHT_CTRL,
    MODIFIER_RIGHT_SHIFT,
    MODIFIER_RIGHT_ALT,
    MODIFIER_RIGHT_META,
    MODIFIER_ALT_GR,
]

KEYCODE_NONE = 0
KEYCODE_A = 0x04
KEYCODE_B = 0x05
KEYCODE_C = 0x06
KEYCODE_D = 0x07
KEYCODE_E = 0x08
KEYCODE_F = 0x09
KEYCODE_G = 0x0A
KEYCODE_H = 0x0B
KEYCODE_I = 0x0C
KEYCODE_J = 0x0D
KEYCODE_K = 0x0E
KEYCODE_L = 0x0F
KEYCODE_M = 0x10
KEYCODE_N = 0x11
KEYCODE_O = 0x12
KEYCODE_P = 0x13
KEYCODE_Q = 0x14
KEYCODE_R = 0x15
KEYCODE_S = 0x16
KEYCODE_T = 0x17
KEYCODE_U = 0x18
KEYCODE_V = 0x19
KEYCODE_W = 0x1A
KEYCODE_X = 0x1B
KEYCODE_Y = 0x1C
KEYCODE_Z = 0x1D
KEYCODE_NUMBER_1 = 0x1E
KEYCODE_NUMBER_2 = 0x1F
KEYCODE_NUMBER_3 = 0x20
KEYCODE_NUMBER_4 = 0x21
KEYCODE_NUMBER_5 = 0x22
KEYCODE_NUMBER_6 = 0x23
KEYCODE_NUMBER_7 = 0x24
KEYCODE_NUMBER_8 = 0x25
KEYCODE_NUMBER_9 = 0x26
KEYCODE_NUMBER_0 = 0x27
KEYCODE_ENTER = 0x28
KEYCODE_ESCAPE = 0x29
KEYCODE_BACKSPACE_DELETE = 0x2A
KEYCODE_TAB = 0x2B
KEYCODE_SPACEBAR = 0x2C
KEYCODE_MINUS = 0x2D
KEYCODE_EQUAL_SIGN = 0x2E
KEYCODE_LEFT_BRACKET = 0x2F
KEYCODE_RIGHT_BRACKET = 0x30
KEYCODE_BACKSLASH = 0x31
KEYCODE_HASH = 0x32
KEYCODE_SEMICOLON = 0x33
KEYCODE_SINGLE_QUOTE = 0x34
KEYCODE_ACCENT_GRAVE = 0x35
KEYCODE_COMMA = 0x36
KEYCODE_PERIOD = 0x37
KEYCODE_FORWARD_SLASH = 0x38
KEYCODE_CAPS_LOCK = 0x39
KEYCODE_F1 = 0x3A
KEYCODE_F2 = 0x3B
KEYCODE_F3 = 0x3C
KEYCODE_F4 = 0x3D
KEYCODE_F5 = 0x3E
KEYCODE_F6 = 0x3F
KEYCODE_F7 = 0x40
KEYCODE_F8 = 0x41
KEYCODE_F9 = 0x42
KEYCODE_F10 = 0x43
KEYCODE_F11 = 0x44
KEYCODE_F12 = 0x45
KEYCODE_PRINT_SCREEN = 0x46
KEYCODE_SCROLL_LOCK = 0x47
KEYCODE_PAUSE_BREAK = 0x48
KEYCODE_INSERT = 0x49
KEYCODE_HOME = 0x4A
KEYCODE_PAGE_UP = 0x4B
KEYCODE_DELETE = 0x4C
KEYCODE_END = 0x4D
KEYCODE_PAGE_DOWN = 0x4E
KEYCODE_RIGHT_ARROW = 0x4F
KEYCODE_LEFT_ARROW = 0x50
KEYCODE_DOWN_ARROW = 0x51
KEYCODE_UP_ARROW = 0x52
KEYCODE_CLEAR = 0x53
KEYCODE_NUM_LOCK = 0x53
KEYCODE_NUMPAD_DIVIDE = 0x54
KEYCODE_NUMPAD_MULTIPLY = 0x55
KEYCODE_NUMPAD_MINUS = 0x56
KEYCODE_NUMPAD_PLUS = 0x57
KEYCODE_NUMPAD_ENTER = 0x58
KEYCODE_NUMPAD_1 = 0x59
KEYCODE_NUMPAD_2 = 0x5A
KEYCODE_NUMPAD_3 = 0x5B
KEYCODE_NUMPAD_4 = 0x5C
KEYCODE_NUMPAD_5 = 0x5D
KEYCODE_NUMPAD_6 = 0x5E
KEYCODE_NUMPAD_7 = 0x5F
KEYCODE_NUMPAD_8 = 0x60
KEYCODE_NUMPAD_9 = 0x61
KEYCODE_NUMPAD_0 = 0x62
KEYCODE_NUMPAD_DOT = 0x63
KEYCODE_102ND = 0x64  # Right of left Shift on non-US keyboards
KEYCODE_CONTEXT_MENU = 0x65
KEYCODE_F13 = 0x68
KEYCODE_F14 = 0x69
KEYCODE_F15 = 0x6A
KEYCODE_F16 = 0x6B
KEYCODE_F17 = 0x6C
KEYCODE_F18 = 0x6D
KEYCODE_F19 = 0x6E
KEYCODE_F20 = 0x6F
KEYCODE_F21 = 0x70
KEYCODE_F22 = 0x71
KEYCODE_F23 = 0x72
KEYCODE_EXECUTE = 0x74
KEYCODE_HELP = 0x75
KEYCODE_SELECT = 0x77
KEYCODE_INTL_RO = 0x87
KEYCODE_INTL_YEN = 0x89
KEYCODE_HANGEUL = 0x90
KEYCODE_HANJA = 0x91
KEYCODE_LEFT_CTRL = 0xE0
KEYCODE_LEFT_SHIFT = 0xE1
KEYCODE_LEFT_ALT = 0xE2
KEYCODE_LEFT_META = 0xE3
KEYCODE_RIGHT_CTRL = 0xE4
KEYCODE_RIGHT_SHIFT = 0xE5
KEYCODE_RIGHT_ALT = 0xE6
KEYCODE_RIGHT_META = 0xE7
KEYCODE_MEDIA_PLAY_PAUSE = 0xE8
KEYCODE_REFRESH = 0xFA
KEYCODE_MEDIA_PREV_TRACK = 0xEA
KEYCODE_MEDIA_NEXT_TRACK = 0xEB
KEYCODE_VOLUME_MUTE = 0xEF
KEYCODE_VOLUME_UP = 0xED
KEYCODE_VOLUME_DOWN = 0xEE


@dataclasses.dataclass
class Keystroke:
    keycode: int
    modifier: int = KEYCODE_NONE
